missing_api_key:
  parameter: "api_key"
  msg: "Api Key is mandatory."

missing_api_secret:
  parameter: "api_secret"
  msg: "Api Secret is mandatory."

invalid_gateway_nonce:
  parameter: "gateway_nonce"
  msg: "Gateway Nonce is invalid."

invalid_gateway_type:
  parameter: "gateway_type"
  msg: "Gateway Type is invalid."

invalid_payment_nonce_uuid:
  parameter: "payment_nonce_uuid"
  msg: "Payment Nonce UUID is invalid."

missing_customer_id:
  parameter: "missing_customer_id"
  msg: "Customer ID is missing."