client:
  client_details:
    key_template: 'client_detail_%{id}'
    expiry_in_seconds: 86400

  api_key_details:
    key_template: 'client_api_key_detail_%{api_key}'
    expiry_in_seconds: 86400

customer:
  get_by_id:
    key_template: 'customer_%{id}'
    expiry_in_seconds: 86400

gateway_nonce:
  get_by_uuid:
    key_template: 'gateway_nonce_%{uuid}'
    expiry_in_seconds: 86400

gateway_detail:
  get_active_by_client_id_and_g_type:
    key_template: 'gateway_detail_%{client_id}_%{gateway_type}'
    expiry_in_seconds: 86400

gateway_customer_association:
  get_all_by_customer_id:
    key_template: 'gateway_customer_association_all_active_%{customer_id}'
    expiry_in_seconds: 86400

ost_payment_token:
  get_by_token:
    key_template: 'ost_payment_token_by_tkn_%{token}'
    expiry_in_seconds: 86400