client:
  client_details:
    key_template: 'client_detail_%{id}'
    expiry_in_seconds: 86400

  api_key_details:
    key_template: 'client_api_key_detail_%{api_key}'
    expiry_in_seconds: 86400

customer:
  get_by_id:
    key_template: 'customer_%{id}'
    expiry_in_seconds: 86400

gateway_nonce:
  get_by_uuid:
    key_template: 'gateway_nonce_%{uuid}'
    expiry_in_seconds: 86400

gateway_detail:
  get_active_by_c_id_and_g_type:
    key_template: 'gateway_detail_%{client_id}_%{gateway_type}'
    expiry_in_seconds: 86400