client:
  client_details:
    key_template: 'client_detail_%{id}'
    expiry_in_seconds: 86400

  api_key_details:
    key_template: 'client_api_key_detail_%{api_key}'
    expiry_in_seconds: 86400

customer:
  get_by_id:
    key_template: 'customer_%{id}'
    expiry_in_seconds: 86400